export const PRODUCTS = [
  // ─── PANELES Y LUCES ───────────────────────────────────────────────
  {
    id: "panel-u880",
    nombre: "Panel de luz PRO LED U-880 PROFESIONAL",
    descripcion: "Panel LED profesional U-880, incluye trípode de 2.10m, 2 baterías recargables y obsequio sorpresa. Ideal para streamers, youtubers y fotógrafos que necesitan iluminación de nivel profesional.",
    precio: 199900,
    precioAntes: 220000,
    descuento: "9%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/0274D1A6-3C7F-4557-8854-613CFA302E06.jpg?v=1778264625&width=800",
    slug: "panel-pro-led-800-profesional-tripode-2-10",
    envioGratis: true,
  },
  {
    id: "panel-u600-tripode",
    nombre: "Panel LED profesional U600 RGB multicolor + trípode",
    descripcion: "Panel LED U600 con colores RGB multicolor, incluye trípode profesional. Perfecto para videos con ambientes de color.",
    precio: 149900,
    precioAntes: 250000,
    descuento: "40%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/panel-led-profesional-u600-rgb-multicolor-tripode-2807127.jpg?v=1774575323&width=800",
    slug: "panel-led-profesional-tripode",
    envioGratis: false,
  },
  {
    id: "panel-u600-tripode-v2",
    nombre: "Panel LED U600 RGB multicolor + trípode (edición especial)",
    descripcion: "Nueva versión del panel U600 RGB con trípode incluido. Mayor luminosidad y control de temperatura de color.",
    precio: 170000,
    precioAntes: 250000,
    descuento: "32%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/91062CC3-7F35-4647-A470-F8F768ED33FA.jpg?v=1778599768&width=800",
    slug: "panel-led-profesional-u600-rgb-multicolor-tripode-copia",
    envioGratis: false,
  },
  {
    id: "panel-led-416",
    nombre: "Panel LED-416 varicolor PRO portátil recargable",
    descripcion: "Panel LED portátil con variación de color (frío/cálido/neutro), recargable vía USB. Ideal para grabar en exteriores sin necesidad de toma de corriente.",
    precio: 120000,
    precioAntes: 169900,
    descuento: "29%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/panel-led-416-varicolor-pro-portatil-recargable-1422096-_1.png?v=1777146178&width=800",
    slug: "panel-led-portatil-recargable-led-416",
    envioGratis: false,
  },
  {
    id: "luz-ym300",
    nombre: "Luz LED YM300 recargable + sorpresa",
    descripcion: "Luz LED YM300 recargable, altura de hasta 1.9m con trípode incluido. Trae un obsequio sorpresa. Excelente relación calidad/precio para creadores en crecimiento.",
    precio: 99900,
    precioAntes: 140000,
    descuento: "29%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/29451C2F-4435-4D9A-90A3-69958C52A1D6.jpg?v=1777584638&width=800",
    slug: "tripode-con-luz-led-tricolor-recargable-altura-1-9m",
    envioGratis: false,
  },
  {
    id: "luz-rgb-m160-panel",
    nombre: "Luz RGB M-160",
    descripcion: "Panel de luz RGB M-160 compacto y portátil. Colores vibrantes para darle un toque creativo a tus videos y fotos.",
    precio: 79900,
    precioAntes: 129900,
    descuento: "38%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/luz-portatil-rgb-m160-7128576.webp?v=1777945288&width=800",
    slug: "luz-rgb-m-160",
    envioGratis: false,
  },
  {
    id: "luz-portatil-m160",
    nombre: "Luz portátil RGB M160",
    descripcion: "Versión portátil de la luz RGB M160, recargable y de bolsillo. Perfecta para grabar en cualquier lugar.",
    precio: 79900,
    precioAntes: 119900,
    descuento: "33%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/5DA35DB0-B028-4738-AD23-5294349CB0D5.jpg?v=1777144039&width=800",
    slug: "luz-portatil-rgb-m160",
    envioGratis: false,
  },
  {
    id: "aro-rl14",
    nombre: "Aro de luz RL-14 + trípode",
    descripcion: "Aro de luz profesional RL-14 de 14 pulgadas con trípode incluido. Luz uniforme 360° perfecta para reels, TikToks y videollamadas.",
    precio: 140000,
    precioAntes: 170000,
    descuento: "18%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/37FB7E39-800B-4372-8DB1-3D0A3ECA337A.jpg?v=1777425257&width=800",
    slug: "aro-de-luz-rl-14-tripode",
    envioGratis: false,
  },
  {
    id: "luz-led-multicolor",
    nombre: "Luz LED recargable multicolor",
    descripcion: "Luz LED recargable con múltiples colores. Compacta y versátil para darle vida a cualquier escena.",
    precio: 50000,
    precioAntes: 99900,
    descuento: "50%",
    categoria: "Paneles y Luces",
    imagen: "https://elegancecolombia.com/cdn/shop/files/luz-led-recargable-multicolor-6909471.jpg?v=1774565136&width=800",
    slug: "luz-recargable-multi-color-rgb",
    envioGratis: false,
  },

  // ─── MICRÓFONOS ────────────────────────────────────────────────────
  {
    id: "mic-k8-inalambrico",
    nombre: "Micrófono K8 inalámbrico con adaptador doble (Android e iPhone)",
    descripcion: "Micrófono de solapa inalámbrico K8, compatible con Android e iPhone gracias a su adaptador doble. Sin cables que estorben tus grabaciones.",
    precio: 40000,
    precioAntes: 80000,
    descuento: "50%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfono-k8-inalambrico-con-adaptador-doble-para-android-y-iphone-3171411.jpg?v=1774565227&width=800",
    slug: "microfono-k8-inalambrico-con-adaptador-doble-para-android-y-iphone",
    envioGratis: false,
  },
  {
    id: "mic-voltpro-vp701",
    nombre: "Micrófonos para celular VoltPro vp701",
    descripcion: "Micrófono de solapa VoltPro vp701, captación omnidireccional, reducción de ruido. Compatible con la mayoría de celulares.",
    precio: 49900,
    precioAntes: 85000,
    descuento: "41%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/60C97831-0C4C-4C90-87A5-60C8418D89A3-_1.webp?v=1777947951&width=800",
    slug: "microfonos-para-celular-voltpro",
    envioGratis: false,
  },
  {
    id: "mic-voltpro-x2",
    nombre: "Micrófonos para celular x2 VoltPro",
    descripcion: "Pack de 2 micrófonos VoltPro para celular. Ideales para entrevistas, podcast o grabaciones en pareja.",
    precio: 50000,
    precioAntes: 69900,
    descuento: "28%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/D9F4FABB-C9CC-4D5F-AB3E-098CCED24EA1.jpg?v=1777143545&width=800",
    slug: "microfonos-para-celular-x2-voltpro",
    envioGratis: false,
  },
  {
    id: "mic-vp056-doble",
    nombre: "Micrófonos para celular doble + adaptador triple Vp-056",
    descripcion: "Kit doble de micrófonos VP-056 con adaptador triple, compatible con Android, iPhone y PC. Sonido profesional a un precio accesible.",
    precio: 60000,
    precioAntes: 149900,
    descuento: "60%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfonos-para-celular-doble-adaptador-triple-vp-056-6820547.jpg?v=1774576307&width=800",
    slug: "microfono-universal-k15-plus-captura-profesional-en-tus-manos",
    envioGratis: false,
  },
  {
    id: "mic-sx21-tripode",
    nombre: "Micrófonos SX21 + Trípode JC-16 de obsequio",
    descripcion: "Micrófonos SX21 de alta calidad con trípode JC-16 de regalo. Una combinación imbatible para empezar a crear contenido.",
    precio: 149900,
    precioAntes: 210000,
    descuento: "29%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/A57CD279-B279-4284-91B2-8E610A0F2CC4-_1.png?v=1777146056&width=800",
    slug: "microfonos-sx21-tripode-jc-16-obsequio",
    envioGratis: false,
  },
  {
    id: "mic-sx21-magnetico",
    nombre: "Micrófonos redondos SX21 magnéticos doble adaptador (iPhone y Android)",
    descripcion: "Micrófonos SX21 con diseño redondo magnético. Incluye adaptador para iPhone y Android. Fácil de portar y conectar.",
    precio: 149900,
    precioAntes: 165000,
    descuento: "9%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfonos-redondos-sx21-magenticos-6097312.webp?v=1777945163&width=800",
    slug: "microfonos-redondos-sx21-magenticos",
    envioGratis: false,
  },
  {
    id: "mic-peluche-txf11",
    nombre: "Micrófonos peluche TX-F11 x2",
    descripcion: "Micrófonos en forma de peluche TX-F11, vienen en par. Perfectos para creadores de contenido infantil, podcasters creativos o streamers que quieren diferenciarse.",
    precio: 89900,
    precioAntes: 160000,
    descuento: "44%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfonos-peluche-tx-f11-2-9440448.jpg?v=1774577675&width=800",
    slug: "microfonos-peluche-tx-f11",
    envioGratis: false,
  },
  {
    id: "mic-peluche-mmdf19",
    nombre: "Micrófonos de peluche x2 MMD-F19",
    descripcion: "Pack de 2 micrófonos peluche MMD-F19 en distintos diseños. Inalámbricos y con excelente captación de voz.",
    precio: 70000,
    precioAntes: 90000,
    descuento: "22%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfonos-de-peluche-x2-mmd-f19-3221157.webp?v=1777950486&width=800",
    slug: "microfonos-x2-mmd-f19",
    envioGratis: false,
  },
  {
    id: "mic-solapa-cable",
    nombre: "Micrófono de solapa de cable",
    descripcion: "Micrófono de solapa con cable, universal para celulares con entrada de 3.5mm. Económico y confiable para grabaciones del día a día.",
    precio: 15000,
    precioAntes: 25000,
    descuento: "40%",
    categoria: "Micrófonos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/microfono-de-solapa-de-cable-7363611.jpg?v=1774576041&width=800",
    slug: "microfono-de-solapa-de-cable",
    envioGratis: false,
  },

  // ─── TRÍPODES ──────────────────────────────────────────────────────
  {
    id: "tripode-cl07-pantalla",
    nombre: "Trípode con pantalla CL-07",
    descripcion: "Trípode profesional CL-07 con pantalla LCD integrada para monitorear tus grabaciones en tiempo real. Altura ajustable y base sólida.",
    precio: 200000,
    precioAntes: 320000,
    descuento: "38%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/tripode-con-pantalla-cl-07-9586931.jpg?v=1774581985&width=800",
    slug: "tripode-con-pantalla-cl-07",
    envioGratis: true,
  },
  {
    id: "tripode-3366-bluetooth",
    nombre: "Trípode profesional con bluetooth para celular y cámara 3366 (1.50m)",
    descripcion: "Trípode profesional 3366 de 1.50m de altura, con control remoto Bluetooth incluido. Compatible con celular y cámara réflex.",
    precio: 70000,
    precioAntes: 139900,
    descuento: "50%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/A24DB9DC-0D5B-4F14-B385-47B2ADEB60D3.jpg?v=1777144126&width=800",
    slug: "tripode-profesional-con-bluetooth-para-celular-y-camara-3366",
    envioGratis: false,
  },
  {
    id: "tripode-n01-doble-190",
    nombre: "Trípode doble para celular N01 (1.90m)",
    descripcion: "Trípode doble N01 de 1.90m, soporta dos celulares simultáneamente. Ideal para grabaciones multi-ángulo.",
    precio: 145000,
    precioAntes: 190000,
    descuento: "24%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/tripode-doble-para-celular-altura-190-n01-8392402.jpg?v=1774579088&width=800",
    slug: "tripode-doble-para-celular-altura-1-90-n01",
    envioGratis: false,
  },
  {
    id: "tripode-selfie-q07-luz",
    nombre: "Trípode selfie con Bluetooth y luz",
    descripcion: "Trípode selfie con control Bluetooth y luz LED integrada. Extensible hasta 1.30m. Perfecto para viajes y contenido espontáneo.",
    precio: 35000,
    precioAntes: 69900,
    descuento: "50%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/tripode-selfie-con-bluetooth-y-luz-3849074.jpg?v=1774564878&width=800",
    slug: "tripode-selfie-q-07-con-bluetooth-y-luz",
    envioGratis: false,
  },
  {
    id: "tripode-d01-mesa",
    nombre: "Trípode de mesa / selfie con control Bluetooth D-01",
    descripcion: "Mini trípode de mesa o palo selfie D-01 con control Bluetooth. Versátil, compacto y fácil de llevar a cualquier parte.",
    precio: 25000,
    precioAntes: 40000,
    descuento: "38%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/tripode-de-mesa-o-selfie-con-control-bluetooth-d-01-3331359.jpg?v=1774577368&width=800",
    slug: "tripode-de-mesa-o-selfie-con-control-bluetooth-d-01",
    envioGratis: false,
  },
  {
    id: "tripode-jc16-palo",
    nombre: "Trípode / palo selfie JC-16 (1.10m)",
    descripcion: "Palo selfie y trípode 2 en 1 JC-16, extiende hasta 1.10m. Ligero y resistente, ideal para grabaciones en movimiento.",
    precio: 45000,
    precioAntes: 68000,
    descuento: "34%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/tripode-palo-selfie-jc-16-110m-9558226.jpg?v=1774578782&width=800",
    slug: "tripode-palo-selfie-jc-16-1-10m",
    envioGratis: false,
  },
  {
    id: "mini-tripode-m1",
    nombre: "Mini trípode portátil M1",
    descripcion: "Mini trípode de escritorio M1, cabeza de bola flexible 360°. Perfecto para grabaciones desde el escritorio o superficies bajas.",
    precio: 75000,
    precioAntes: 99900,
    descuento: "25%",
    categoria: "Trípodes",
    imagen: "https://elegancecolombia.com/cdn/shop/files/mini-tripode-portatil-m1-1720443.jpg?v=1774577338&width=800",
    slug: "mini-tripode-portatil-m1",
    envioGratis: false,
  },

  // ─── COMBOS ────────────────────────────────────────────────────────
  {
    id: "combo-q07-vp056-rgb",
    nombre: "Combo creadores: trípode Q07 + micrófonos Vp056 + Luz RGB M160",
    descripcion: "El combo ideal para empezar: trípode Q07, micrófonos VP056 y luz RGB M160. Todo lo que necesitas en un solo paquete.",
    precio: 155000,
    precioAntes: 225000,
    descuento: "31%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/combo-para-creadores-de-contenido-tripode-q07-microfonos-vp056-luz-rgb-8102565-_1.webp?v=1777950596&width=800",
    slug: "combo-para-creadores-de-contenido-tripode-q07-microfonos-vp056-luz-rgb",
    envioGratis: false,
  },
  {
    id: "combo-rgb-jc16-k8",
    nombre: "Combo contenido: luz RGB + trípode JC16 + micrófono K8",
    descripcion: "Combo perfecto para creadores: luz RGB portátil, trípode JC16 y micrófono K8. Audio, video e iluminación en uno.",
    precio: 99900,
    precioAntes: 140000,
    descuento: "29%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/431E52FD-CFA6-4E0A-BB48-4163390EFD03-_1.png?v=1777146106&width=800",
    slug: "combo-para-crear-contenido-luz-rgb-tripode-jc16-microfono-k8",
    envioGratis: false,
  },
  {
    id: "combo-x3-k8-mesa-luz",
    nombre: "Combo x3 creadores: micrófono K8 + trípode de mesa con control + luz recargable",
    descripcion: "Combo completo x3: micrófono K8, trípode de mesa con control y luz recargable. Para grabar desde casa como un profesional.",
    precio: 80000,
    precioAntes: 115000,
    descuento: "30%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/combo-x3-para-creadores-microfono-k8-tripode-de-mesa-con-control-luz-recargable-7075576-_1.webp?v=1777944844&width=800",
    slug: "combo-x3-para-creadores-microfono-k8-tripode-de-mesa-con-control-luz-recargable",
    envioGratis: false,
  },
  {
    id: "kit-k8-luz3",
    nombre: "Kit micrófono K8 + Luz con 3 intensidades",
    descripcion: "Kit básico pero potente: micrófono K8 y luz con 3 niveles de intensidad. Perfecto para empezar sin gastar mucho.",
    precio: 60000,
    precioAntes: 99900,
    descuento: "40%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/kit-microfono-k8-luz-con-3-intensidades-3256442-_1.png?v=1777146194&width=800",
    slug: "kit-microfono-k8-luz-con-3-intensidades",
    envioGratis: false,
  },
  {
    id: "kit-completo-creadores",
    nombre: "Kit completo creadores: micrófono + trípode + luz + control Bluetooth",
    descripcion: "El kit más completo para principiantes: micrófono, trípode, luz y control Bluetooth. Todo en uno, a un precio increíble.",
    precio: 50000,
    precioAntes: 99900,
    descuento: "50%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/kit-completo-para-creadores-microfono-tripode-luz-control-bluetooth-2224089.jpg?v=1774572830&width=800",
    slug: "kit-completo-para-creadores-microfono-tripode-luz-control-bluetooth",
    envioGratis: false,
  },
  {
    id: "combo-vp056-rgb",
    nombre: "Combo contenido: micrófono Universal Vp-056 + Luz RGB recargable",
    descripcion: "Combo duo: micrófono VP-056 y luz RGB recargable. Calidad de audio e iluminación colorida en un paquete compacto.",
    precio: 99900,
    precioAntes: 189900,
    descuento: "47%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/combo-contenido-microfono-universal-vp-056-luz-rgb-recargable-1953535-_1.png?v=1777146219&width=800",
    slug: "combo-contenido-microfono-k15-plus-luz-rgb-recargable",
    envioGratis: false,
  },
  {
    id: "combo-m160-jc16",
    nombre: "Combo contenido: Luz M160 RGB + Trípode JC16",
    descripcion: "Combo clásico: luz M160 RGB y trípode JC16. Sencillo, efectivo y con el mejor precio del mercado.",
    precio: 99900,
    precioAntes: 150000,
    descuento: "33%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/combo-para-crear-contenido-luz-m160-rgb-tripode-jc16-9833565.jpg?v=1774581999&width=800",
    slug: "combo-para-crear-contenido-luz-m160-rgb-tripode-cl17",
    envioGratis: false,
  },
  {
    id: "kit-rgb-4en1",
    nombre: "Kit de contenido RGB 4en1",
    descripcion: "Kit 4 en 1 con accesorios RGB para creadores de contenido. Incluye luz, soporte y accesorios complementarios.",
    precio: 50000,
    precioAntes: 75000,
    descuento: "33%",
    categoria: "Combos",
    imagen: "https://elegancecolombia.com/cdn/shop/files/kit-de-contenido-rgb-4en1-7128576.webp?v=1777945288&width=800",
    slug: "kit-de-contenido-rgb-4en1",
    envioGratis: false,
  },

  // ─── ACCESORIOS ────────────────────────────────────────────────────
  {
    id: "adaptador-aux-tipoc",
    nombre: "Adaptador de auxiliar a tipo C",
    descripcion: "Adaptador de 3.5mm auxiliar a USB Tipo C. Imprescindible para conectar micrófonos con cable a celulares modernos.",
    precio: 15000,
    precioAntes: 39900,
    descuento: "62%",
    categoria: "Accesorios",
    imagen: "https://elegancecolombia.com/cdn/shop/files/adaptador-de-auxiliar-a-tipo-c-9235396.jpg?v=1774575971&width=800",
    slug: "adaptador-de-auxiliar-a-tipo-c",
    envioGratis: false,
  },
];

export const ENVIO_GRATIS_DESDE = 199000;
export const COSTO_ENVIO = 18000;

export function formatPrice(price) {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    minimumFractionDigits: 0,
  }).format(price);
}

export function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category) {
  return PRODUCTS.filter((p) => p.categoria === category);
}

export const CATEGORIES = [...new Set(PRODUCTS.map((p) => p.categoria))];
